[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "any"]
set = true

# not working
#[config.custom_keywords]
#opacity = '0.6'

[templates.waybar]
input_path = './templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop'

[templates.cava]
input_path = './templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

[templates.vesktop]
input_path = './templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.mako]
input_path = './templates/mako'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

[templates.zed]
input_path = './templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetify-comfy.ini'
output_path = '~/.config/spicetify/Themes/Comfy/color.ini'
post_hook = 'sh ~/.config/matugen/hooks/spicetify.sh'
